create or replace view
    edwprodhh.hermes.master_config_contact_codes_plgroup
as
select  'ADVOCATE HC - 3P'                                  as pl_group,    'PP Offer'          as collection_type,     'HMHHP'     as letter_code,     NULL        as text_code,   'USUAL'     as voapp_code union all
select  'ASPEN DENTAL - 3P'                                 as pl_group,    'PP Offer'          as collection_type,     'HMHHP'     as letter_code,     NULL        as text_code,   'USUAL'     as voapp_code union all
select  'BAYLOR SCOTT WHITE HEALTHCARE EPIC - 3P'           as pl_group,    'Dun'               as collection_type,     'HMHHSP'    as letter_code,      NULL       as text_code,   'USUAL'     as voapp_code union all
select  'BAYLOR SCOTT WHITE HEALTHCARE EPIC - 3P-2'         as pl_group,    'Dun'               as collection_type,     'HMHHSP'    as letter_code,      NULL       as text_code,   'USUAL'     as voapp_code union all
select  'BROWARD HEALTH - 3P'                               as pl_group,    'PP Offer'          as collection_type,     'HMHHFAC'   as letter_code,     'TXTSMSH1'  as text_code,   'USUAL'     as voapp_code union all
select  'CARLE HEALTHCARE - 3P'                             as pl_group,    'PP Offer'          as collection_type,     'HMHHP'     as letter_code,     'TXTSMSH1'  as text_code,   'USUAL'     as voapp_code union all
select  'CARLE HEALTHCARE - 3P-2'                           as pl_group,    'PP Offer'          as collection_type,     'HMHHP'     as letter_code,     'TXTSMSH1'  as text_code,   'USUAL'     as voapp_code union all
select  'CHILDRENS HOSP OF ATLANTA - 3P'                    as pl_group,    'PP Offer'          as collection_type,     'HMHHCHO'   as letter_code,      NULL       as text_code,   'USUAL'     as voapp_code union all
select  'CHOP - 3P'                                         as pl_group,    'Dun'               as collection_type,     'HMHHC'     as letter_code,      NULL       as text_code,   'USUAL'     as voapp_code union all
select  'CITY OF CLEVELAND OH - CONDUENT - 3P'              as pl_group,    'Dun'               as collection_type,     'EDN1-CLE'  as letter_code,     NULL        as text_code,   NULL        as voapp_code union all
select  'CITY OF LA CA - FINANCE - 3P'                      as pl_group,    NULL                as collection_Type,     NULL        as letter_code,     'TXT-SMS1'  as text_code,   NULL        as voapp_code union all
select  'CITY OF LA CA - PARKING CONDUENT - 3P'             as pl_group,    'Dun'               as collection_type,     'EDN1_LA'   as letter_code,     'TXT1'      as text_code,   NULL        as voapp_code union all
select  'CITY OF PHILADELPHIA PA - MISC - 3P'               as pl_group,    NULL                as collection_Type,     NULL        as letter_code,     'TXT-SMS1'  as text_code,   NULL        as voapp_code union all
select  'CITY OF PHILADELPHIA PA - PARKING - 3P'            as pl_group,    'Dun'               as collection_type,     'EDN1-PP'   as letter_code,     'TXT-SMS1'  as text_code,   NULL        as voapp_code union all
select  'CITY OF SEATTLE WA - MUNI COURT - 3P'              as pl_group,    'Dun'               as collection_type,     'EDN1-SMC'  as letter_code,     'TXT-SMS2'  as text_code,   NULL        as voapp_code union all
select  'CITY OF WASHINGTON DC - ABRA - 3P'                 as pl_group,    NULL                as collection_type,     'DC-GEN1'   as letter_code,     'TXT-SMS'   as text_code,   NULL        as voapp_code union all
select  'CITY OF WASHINGTON DC - BEGA - 3P'                 as pl_group,    NULL                as collection_type,     'DC-GEN1'   as letter_code,     'TXT-SMS'   as text_code,   NULL        as voapp_code union all
-- select  'CITY OF WASHINGTON DC - CCU - 3P'                  as pl_group,    NULL                as collection_type,     'DC-GEN1'   as letter_code,     NULL        as text_code,   NULL        as voapp_code union all
select  'CITY OF WASHINGTON DC - DHCD - 3P'                 as pl_group,    NULL                as collection_type,     'DC-GEN1'   as letter_code,     'TXT-SMS'   as text_code,   NULL        as voapp_code union all
select  'CITY OF WASHINGTON DC - DLCP - 3P'                 as pl_group,    NULL                as collection_type,     'DC-DCRA'   as letter_code,     'TXT-SMS'   as text_code,   NULL        as voapp_code union all
select  'CITY OF WASHINGTON DC - DMV - 3P'                  as pl_group,    NULL                as collection_type,     'DC-DMV1'   as letter_code,     'TXT-SMS'   as text_code,   NULL        as voapp_code union all
select  'CITY OF WASHINGTON DC - DOB - 3P'                  as pl_group,    NULL                as collection_type,     'DC-DCRA'   as letter_code,     'TXT-SMS'   as text_code,   NULL        as voapp_code union all
select  'CITY OF WASHINGTON DC - DOC - 3P'                  as pl_group,    NULL                as collection_type,     'DC-GEN1'   as letter_code,     'TXT-SMS'   as text_code,   NULL        as voapp_code union all
select  'CITY OF WASHINGTON DC - DOEE - 3P'                 as pl_group,    NULL                as collection_type,     'DC-GEN1'   as letter_code,     'TXT-SMS'   as text_code,   NULL        as voapp_code union all
select  'CITY OF WASHINGTON DC - FEMS - 3P'                 as pl_group,    NULL                as collection_type,     'DC-GEN1'   as letter_code,     'TXT1-SMS'  as text_code,   NULL        as voapp_code union all
select  'CITY OF WASHINGTON DC - MPD - 3P'                  as pl_group,    NULL                as collection_type,     'DC-GEN1'   as letter_code,     'TXT-SMS'   as text_code,   NULL        as voapp_code union all
select  'CITY OF WASHINGTON DC - OAG - 3P'                  as pl_group,    NULL                as collection_type,     'DC-GEN1'   as letter_code,     'TXT-SMS'   as text_code,   NULL        as voapp_code union all
select  'CITY OF WASHINGTON DC - OLG - 3P'                  as pl_group,    NULL                as collection_type,     'DC-GEN1'   as letter_code,     'TXT-SMS'   as text_code,   NULL        as voapp_code union all
select  'CITY OF WASHINGTON DC - OP - 3P'                   as pl_group,    NULL                as collection_type,     'DC-GEN1'   as letter_code,     'TXT-SMS'   as text_code,   NULL        as voapp_code union all
select  'CITY OF WASHINGTON DC - OSSE - 3P'                 as pl_group,    NULL                as collection_type,     'DC-GEN1'   as letter_code,     'TXT-SMS'   as text_code,   NULL        as voapp_code union all
select  'COC - BUILDINGS'                                   as pl_group,    'Dun'               as collection_type,     'CTYBLG1'   as letter_code,     NULL        as text_code,   NULL        as voapp_code union all
select  'COC - PARKING'                                     as pl_group,    'Dun'               as collection_type,     'CTY14-1'   as letter_code,     NULL        as text_code,   NULL        as voapp_code union all
select  'COC - WATER'                                       as pl_group,    'Dun'               as collection_type,     NULL        as letter_code,     NULL        as text_code,   NULL        as voapp_code union all
select  'COC - TAX'                                         as pl_group,    'Dun'               as collection_type,     'CTYTAX1'   as letter_code,     NULL        as text_code,   NULL        as voapp_code union all
select  'COLUMBIA DENTAL - 3P'                              as pl_group,    NULL                as collection_type,     'HMHHCDL'   as letter_code,     'TXTNY01'   as text_code,   NULL        as voapp_code union all
select  'COLUMBIA DOCTORS - 3P'                             as pl_group,    'Dun'               as collection_type,     'HMHHCD'    as letter_code,     'TXTNY01'   as text_code,   NULL        as voapp_code union all
select  'COUNTY OF LOS ANGELES CA - 3P'                     as pl_group,    'Dun'               as collection_type,     'ECCFTAP1'  as letter_code,     NULL        as text_code,   NULL        as voapp_code union all
select  'COUNTY OF CHAMPAIGN IL - 3P'                       as pl_group,    NULL                as collection_type,     NULL        as letter_code,     'TXT-SMS'   as text_code,   NULL        as voapp_code union all
select  'COUNTY OF DEKALB IL - 3P'                          as pl_group,    NULL                as collection_type,     NULL        as letter_code,     'TXT-SMS'   as text_code,   NULL        as voapp_code union all
select  'COUNTY OF DUPAGE IL - 3P'                          as pl_group,    NULL                as collection_type,     NULL        as letter_code,     'TXT-SMS'   as text_code,   NULL        as voapp_code union all
select  'COUNTY OF DUVAL FL - 3P'                           as pl_group,    NULL                as collection_type,     NULL        as letter_code,     'TXT-SMS'   as text_code,   NULL        as voapp_code union all
select  'COUNTY OF KANE IL - 3P'                            as pl_group,    NULL                as collection_type,     NULL        as letter_code,     'TXT-SMS'   as text_code,   NULL        as voapp_code union all
select  'COUNTY OF KANKAKEE IL - 3P'                        as pl_group,    NULL                as collection_type,     NULL        as letter_code,     'TXT-SMS'   as text_code,   NULL        as voapp_code union all
select  'COUNTY OF KENDALL IL - 3P'                         as pl_group,    NULL                as collection_type,     NULL        as letter_code,     'TXT-SMS'   as text_code,   NULL        as voapp_code union all
select  'COUNTY OF LAKE IL - 3P'                            as pl_group,    NULL                as collection_type,     NULL        as letter_code,     'TXT-SMS'   as text_code,   NULL        as voapp_code union all
select  'COUNTY OF LASALLE IL - 3P'                         as pl_group,    NULL                as collection_type,     NULL        as letter_code,     'TXT-SMS'   as text_code,   NULL        as voapp_code union all
select  'COUNTY OF LEE IL - 3P'                             as pl_group,    NULL                as collection_type,     NULL        as letter_code,     'TXT-SMS'   as text_code,   NULL        as voapp_code union all
select  'COUNTY OF MADISON IL - 3P'                         as pl_group,    NULL                as collection_type,     NULL        as letter_code,     'TXT-SMS'   as text_code,   NULL        as voapp_code union all
select  'COUNTY OF MCHENRY IL - 3P'                         as pl_group,    NULL                as collection_type,     NULL        as letter_code,     'TXT-SMS'   as text_code,   NULL        as voapp_code union all
select  'COUNTY OF POLK FL - 3P'                            as pl_group,    NULL                as collection_type,     NULL        as letter_code,     'TXT1'      as text_code,   NULL        as voapp_code union all
select  'COUNTY OF SANGAMON IL - 3P'                        as pl_group,    NULL                as collection_type,     NULL        as letter_code,     'TXT-SMS'   as text_code,   NULL        as voapp_code union all
select  'COUNTY OF SARASOTA FL - 3P'                        as pl_group,    NULL                as collection_type,     NULL        as letter_code,     'TXT-CNTY'  as text_code,   NULL        as voapp_code union all
select  'COUNTY OF VENTURA CA - 3P'                         as pl_group,    NULL                as collection_type,     NULL        as letter_code,     'TXT-SMS'   as text_code,   NULL        as voapp_code union all
select  'COUNTY OF WILL IL - 3P'                            as pl_group,    NULL                as collection_type,     NULL        as letter_code,     'TXT-CNTY'  as text_code,   NULL        as voapp_code union all
select  'COUNTY OF WINNEBAGO IL - 3P'                       as pl_group,    NULL                as collection_type,     NULL        as letter_code,     'TXT-SMS'   as text_code,   NULL        as voapp_code union all
select  'ELIZABETH RIVER CROSSINGS - 3P'                    as pl_group,    'Dun'               as collection_type,     'ERC1'      as letter_code,     'TXT-ERC'   as text_code,   NULL        as voapp_code union all
select  'EVERGY - 3P'                                       as pl_group,    'PP Offer'          as collection_type,     'HMHHUP'    as letter_code,     NULL        as text_code,   'USUAL'     as voapp_code union all
select  'EVERGY - 3P-2'                                     as pl_group,    'PP Offer'          as collection_type,     'HMHHUP'    as letter_code,     NULL        as text_code,   'USUAL'     as voapp_code union all
select  'FRANCISCAN HEALTH - 3P'                            as pl_group,    'PP Offer'          as collection_type,     'HMHHP'     as letter_code,     'TXTSMSH1'  as text_code,   'USUAL'     as voapp_code union all
select  'HEALTHPARTNERS - 3P'                               as pl_group,    'Dun'               as collection_type,     'HMHHP'     as letter_code,     NULL        as text_code,   NULL        as voapp_code union all
select  'HEALTHPARTNERS - 3P-2'                             as pl_group,    'Dun'               as collection_type,     'HMHHP'     as letter_code,     NULL        as text_code,   NULL        as voapp_code union all
select  'HEALTHPARTNERS WI - 3P'                            as pl_group,    'Dun'               as collection_type,     'HMHHP'     as letter_code,     NULL        as text_code,   NULL        as voapp_code union all
select  'HEALTHPARTNERS WI - 3P-2'                          as pl_group,    'Dun'               as collection_type,     'HMHHP'     as letter_code,     NULL        as text_code,   NULL        as voapp_code union all
select  'INGALLS MEMORIAL HOSPITAL - 3P'                    as pl_group,    'Dun'               as collection_type,     'HMHHP'     as letter_code,     NULL        as text_code,   NULL        as voapp_code union all
select  'IU HEALTH - 3P'                                    as pl_group,    'Dun'               as collection_type,     'HMHHP'     as letter_code,     'TXTSMSH1'  as text_code,   'USUAL'     as voapp_code union all
select  'IU SURGICAL CARE AFF - 3P'                         as pl_group,    'PP/SIF Offer'      as collection_type,     'HMHHSP'    as letter_code,     NULL        as text_code,   'USUAL'     as voapp_code union all
select  'LOYOLA UNIV HEALTH SYSTEM - 3P'                    as pl_group,    'PP Offer'          as collection_type,     'HMHHP'     as letter_code,      NULL       as text_code,   'USUAL'     as voapp_code union all
select  'MCLEOD HEALTH - 3P'                                as pl_group,    'PP Offer'          as collection_type,     'HMHHP'     as letter_code,     'TXTSMSH1'  as text_code,   'USUAL'     as voapp_code union all
select  'MD ANDERSON - 3P'                                  as pl_group,    'Dun'               as collection_type,     'HMHHP'     as letter_code,     NULL        as text_code,   NULL        as voapp_code union all
select  'MD ANDERSON - 3P-2'                                as pl_group,    'Dun'               as collection_type,     'AVC2PC'    as letter_code,     NULL        as text_code,   NULL        as voapp_code union all
select  'MOUNT SINAI - 3P'                                  as pl_group,    'Dun'               as collection_type,     'HMHHN'     as letter_code,     'TXTNY01'   as text_code,   NULL        as voapp_code union all
select  'NORTHSHORE UNIV HEALTH - 3P'                       as pl_group,    'PP Offer'          as collection_type,     'HMHHP'     as letter_code,     'TXTSMSH1'  as text_code,   'USUAL'     as voapp_code union all
select  'NORTHWESTERN MEDICINE - 3P'                        as pl_group,    'PP Offer'          as collection_type,     'HMHHP'     as letter_code,     'TXTSMSH1'  as text_code,   'USUAL'     as voapp_code union all
select  'NW COMM HOSP - 3P'                                 as pl_group,    'PP Offer'          as collection_type,     'HMHHP'     as letter_code,     'TXTSMSH1'  as text_code,   'USUAL'     as voapp_code union all
select  'NW COMM HOSP - 3P-2'                               as pl_group,    'PP Offer'          as collection_type,     'HMHHP'     as letter_code,     'TXTSMSH1'  as text_code,   'USUAL'     as voapp_code union all
select  'PALOS HEALTH - 3P'                                 as pl_group,    'PP Offer'          as collection_type,     'HMHHP'     as letter_code,     'TXTSMSH1'  as text_code,   'USUAL'     as voapp_code union all
select  'PRISMA HEALTH - 3P'                                as pl_group,    'PP Offer'          as collection_type,     'HMHHP'     as letter_code,     'TXTSMSH1'  as text_code,   'USUAL'     as voapp_code union all
select  'PRISMA HEALTH - 3P-2'                              as pl_group,    'PP Offer'          as collection_type,     'HMHHP'     as letter_code,     'TXTSMSH1'  as text_code,   'USUAL'     as voapp_code union all
select  'PRISMA HEALTH UNIVERSITY - 3P'                     as pl_group,    'Dun'               as collection_type,     'AVC2P'     as letter_code,     'TXTSMSH1'  as text_code,   'USUAL'     as voapp_code union all
select  'PROMEDICA HS - 3P-2'                               as pl_group,    'PP Offer'          as collection_type,     'HMHHP'     as letter_code,      NULL       as text_code,   'USUAL'     as voapp_code union all
select  'PROVIDENCE ST JOSEPH HEALTH - 3P'                  as pl_group,    'PP Offer'          as collection_type,     'HMHHP'     as letter_code,     'TXTSMSH1'  as text_code,   'USUAL'     as voapp_code union all
select  'PROVIDENCE ST JOSEPH HEALTH - 3P-2'                as pl_group,    'PP Offer'          as collection_type,     'HMHHP'     as letter_code,     NULL        as text_code,   'USUAL'     as voapp_code union all
select  'SHIRLEY RYAN ABILITY LABS - 3P'                    as pl_group,    'PP Offer'          as collection_type,     'HMHHP'     as letter_code,     NULL        as text_code,   'USUAL'     as voapp_code union all
select  'SILVER CROSS - 3P'                                 as pl_group,    'PP Offer'          as collection_type,     'HMHHP'     as letter_code,     NULL        as text_code,   'USUAL'     as voapp_code union all
select  'SILVER CROSS - HEALTH SYSTEM SERVICES INC - 3P'    as pl_group,    'PP Offer'          as collection_type,     'HMHHP'     as letter_code,     NULL        as text_code,   'USUAL'     as voapp_code union all
select  'ST ELIZABETH HEALTHCARE - 3P'                      as pl_group,    'PP Offer'          as collection_type,     'HMHHP'     as letter_code,     NULL        as text_code,   'USUAL'     as voapp_code union all
select  'STATE OF AZ - FARE - CONDUENT - 3P'                as pl_group,    NULL                as collection_Type,     NULL        as letter_code,     'TXT-SMS1'  as text_code,   NULL        as voapp_code union all
select  'STATE OF IL - DOR - 3P'                            as pl_group,    'Dun'               as collection_type,     'ESOI3'     as letter_code,     'TXT1IC'    as text_code,   'USUAL'     as voapp_code union all
select  'STATE OF IL - DOR - 3P-2'                          as pl_group,    'Dun'               as collection_type,     'ESOI3'     as letter_code,     'TXT1IC'    as text_code,   'USUAL'     as voapp_code union all
select  'STATE OF KS - DOR - 3P'                            as pl_group,    'Dun'               as collection_type,     'E-KSS3'    as letter_code,     'TXT3IC'    as text_code,   'USUAL'     as voapp_code union all
select  'STATE OF OK - TAX COMMISSION - 3P'                 as pl_group,    'Dun'               as collection_type,     'OTC3'      as letter_code,     'TXT1IC'    as text_code,   'USUAL'     as voapp_code union all
select  'STATE OF PA - TURNPIKE COMMISSION - 3P'            as pl_group,    'Dun'               as collection_type,     'PATC1'     as letter_code,     'TXT-SMS1'  as text_code,   NULL        as voapp_code union all
select  'STATE OF VA - DOT - 3P'                            as pl_group,    'Dun'               as collection_type,     'VATAX4'    as letter_code,      NULL       as text_code,   'USUAL'     as voapp_code union all
select  'STATE OF VA - DOT - 3P-2'                          as pl_group,    'Dun'               as collection_type,     'VATAX4'    as letter_code,      NULL       as text_code,   'USUAL'     as voapp_code union all
select  'SWEDISH HOSPITAL - 3P'                             as pl_group,    'PP/SIF Offer'      as collection_type,     'HMHHSP'    as letter_code,     'TXTSMSH1'  as text_code,   'USUAL'     as voapp_code union all
select  'TPC - SHANNON - HOSP - 3P-2'                       as pl_group,    'PP/SIF Offer'      as collection_type,     'HMHHSP'    as letter_code,     NULL        as text_code,   'USUAL'     as voapp_code union all
select  'TPC - SHANNON - PHY - 3P-2'                        as pl_group,    'PP/SIF Offer'      as collection_type,     'HMHHSP'    as letter_code,      NULL       as text_code,   'USUAL'     as voapp_code union all
select  'TPC - UNITED REGIONAL - 3P'                        as pl_group,    'Dun'               as collection_type,     'AVC2P'     as letter_code,     NULL        as text_code,   'USUAL'     as voapp_code union all
select  'U OF CHICAGO MEDICAL - 3P'                         as pl_group,    'PP Offer'          as collection_type,     'HMHHP'     as letter_code,     'TXTSMSH1'  as text_code,   'USUAL'     as voapp_code union all
select  'U OF CINCINNATI HEALTH SYSTEM - 3P'                as pl_group,    'Dun'               as collection_type,     'HMHHPUC'   as letter_code,     'TXT1'      as text_code,   'USUAL'     as voapp_code union all
select  'U OF IL AT CHICAGO - 3P'                           as pl_group,    'PP Offer'          as collection_type,     'HMHHP'     as letter_code,      NULL       as text_code,   'USUAL'     as voapp_code union all
select  'UNITED REGIONAL - 3P-2'                            as pl_group,    'Dun'               as collection_type,     'AVC2P'     as letter_code,     NULL        as text_code,   'USUAL'     as voapp_code union all
select  'UNIVERSAL HEALTH SERVICES - 3P'                    as pl_group,    'Dun'               as collection_type,     'HMHHU'     as letter_code,     'TXTSIF01'  as text_code,   'USUAL'     as voapp_code union all
select  'WEILL CORNELL PHY - 3P'                            as pl_group,    NULL                as collection_type,     'HMHHN'     as letter_code,     'TXTNY01'   as text_code,   NULL        as voapp_code
;