select      execute_time,
            count(*)                                                                                                                                                                                                                                                                                                as n,
            sum(pass_client_active_hermes_contacts                                                                                                                                                                                                                                                              )   as pass_client_active_hermes_contacts_,
            sum(pass_client_active_hermes_contacts * pass_client_allowed_voapps                                                                                                                                                                                                                                 )   as pass_client_allowed_voapps_,
            sum(pass_client_active_hermes_contacts * pass_client_allowed_voapps * pass_validation_requirement_nonoffer                                                                                                                                                                                          )   as pass_validation_requirement_nonoffer_,
            sum(pass_client_active_hermes_contacts * pass_client_allowed_voapps * pass_validation_requirement_nonoffer * pass_debtor_status                                                                                                                                                                     )   as pass_debtor_status_,
            sum(pass_client_active_hermes_contacts * pass_client_allowed_voapps * pass_validation_requirement_nonoffer * pass_debtor_status * pass_debtor_active                                                                                                                                                )   as pass_debtor_active_,
            sum(pass_client_active_hermes_contacts * pass_client_allowed_voapps * pass_validation_requirement_nonoffer * pass_debtor_status * pass_debtor_active * pass_phone_voapps                                                                                                                            )   as pass_phone_voapps_,
            sum(pass_client_active_hermes_contacts * pass_client_allowed_voapps * pass_validation_requirement_nonoffer * pass_debtor_status * pass_debtor_active * pass_phone_voapps * pass_debtor_balance                                                                                                      )   as pass_debtor_balance_,
            sum(pass_client_active_hermes_contacts * pass_client_allowed_voapps * pass_validation_requirement_nonoffer * pass_debtor_status * pass_debtor_active * pass_phone_voapps * pass_debtor_balance * pass_packet_balance                                                                                )   as pass_packet_balance_,
            sum(pass_client_active_hermes_contacts * pass_client_allowed_voapps * pass_validation_requirement_nonoffer * pass_debtor_status * pass_debtor_active * pass_phone_voapps * pass_debtor_balance * pass_packet_balance * pass_debtor_age_packet                                                       )   as pass_debtor_age_packet_,
            sum(pass_client_active_hermes_contacts * pass_client_allowed_voapps * pass_validation_requirement_nonoffer * pass_debtor_status * pass_debtor_active * pass_phone_voapps * pass_debtor_balance * pass_packet_balance * pass_debtor_age_packet * pass_voapps_cooldown                                )   as pass_voapps_cooldown_,
            sum(pass_client_active_hermes_contacts * pass_client_allowed_voapps * pass_validation_requirement_nonoffer * pass_debtor_status * pass_debtor_active * pass_phone_voapps * pass_debtor_balance * pass_packet_balance * pass_debtor_age_packet * pass_voapps_cooldown * pass_delay_voapps            )   as pass_delay_voapps_,
            sum(pass_client_active_hermes_contacts * pass_client_allowed_voapps * pass_validation_requirement_nonoffer * pass_debtor_status * pass_debtor_active * pass_phone_voapps * pass_debtor_balance * pass_packet_balance * pass_debtor_age_packet * pass_voapps_cooldown * pass_delay_voapps * pass_7in7)   as pass_7in7_,
            sum(is_eligible_voapps                                                                                                                                                                                                                                                                              )   as is_eligible_voapps_
from        edwprodhh.hermes.master_prediction_pool_log as pool
where       pl_group = 'IU HEALTH - 3P'            
group by    1
order by    1 desc
;